Description:  This template deploys an S3 bucket for storage of recipes.

Resources:
  S3BucketRecipesFreeAAM:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [ "cand-c3-free-recipes-aam", !Ref 'AWS::AccountId' ] ]
  S3BucketRecipesSecretAAM:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [ "cand-c3-secret-recipes-aam", !Ref 'AWS::AccountId' ] ]
  S3BucketVPCFlowLogsAAM:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Join [ "-", [ "cand-c3-vpc-flow-logs-aam", !Ref 'AWS::AccountId' ] ]

Outputs:
  BucketNameRecipesFree:
    Value: !Ref 'S3BucketRecipesFreeAAM'
    Description: Name of the Amazon S3 bucket that you will upload free recipes to.
    Export:
      Name: BucketNameRecipesFreeAAM
  BucketNameRecipesSecret:
    Value: !Ref 'S3BucketRecipesSecretAAM'
    Description: Name of the Amazon S3 bucket that you will upload secret recipes to.
    Export:
      Name: BucketNameRecipesSecretAAM
  BucketArnVPCFlowLogs:
    Value: !GetAtt S3BucketVPCFlowLogsAAM.Arn
    Description: Arn of the Amazon S3 bucket that have vpc flow logs for this project
    Export:
      Name: BucketArnVPCFlowLogsAAM
